---
title: "CoronaVirus"
author: "Sajed Sallay"
date: "9/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(coronavirus)
library(leaflet)
library(tidyverse)
library(lubridate)
library(visdat)
library(inspectdf)
```



```{r}
covid_ow <- read_csv(here::here("data/owid-covid-data.csv"))
covid_j <- read_csv(here::here("data/tabel_id_data.csv"))
covid_d <-read_csv(here::here("data/covid_31Aug2021.csv"))
covid_n <- read_csv(here::here("data/df-with-provinsi.csv"))


## remove , and replace with . in covid_j

covid_j <- covid_j %>%
  pivot_wider(names_from = `Measure Names`, values_from = `Measure Values`)


ow <- covid_ow %>%
  filter(location == "Indonesia")
```



```{r}
ow %>% 
  select(location,date,total_cases,new_cases,new_deaths,new_vaccinations) %>%
  DT::datatable(filter = 'top',
    rownames = TRUE,
    colnames = c("Country", "Date", "Total Cases", "New Cases", "New Deaths", "New Vaccinations"),
    options = list(
      pageLength = 5
    ),
    class = 'cell-border stripe'
  )
```


```{r}
ow1 <- ow %>% 
  
  select(location, date, total_cases_per_million, new_cases_per_million,
         total_tests_per_thousand, weekly_icu_admissions_per_million,
          weekly_hosp_admissions_per_million,
         hosp_patients_per_million, hospital_beds_per_thousand) %>%
  
  mutate(total_tests_per_million = (total_tests_per_thousand * 1000),
          hospital_beds_per_million = (hospital_beds_per_thousand * 1000)) %>%
  
  select(location,date,total_cases_per_million, ends_with("per_million"))
         

```


```{r}
vis_dat(ow1)

```


```{r}
covid_d %>%
  arrange(desc(`Cases Per 100,000`)) %>%
  head(5)
  
```






```{r}
library(kableExtra)

covid_d %>%
  arrange(desc(`Cases Per 100,000`)) %>%
  head(5) %>%
  select(District,`Cases Per 100,000`,`Hospitalisation Per 100,000`,
         `test per 100,000`,`treatment per 100,000`) %>%
  kbl() %>%
    kable_minimal()

```


```{r}
ow %>% 
  mutate(`Total Cases` = scales::comma(total_cases, accuracy= 1),
         `New Cases` = scales::comma(new_cases, accuracy = 1),
         `New Deaths` = scales::comma(new_deaths, accuracy = 1),
         `New Vaccinations` = scales::comma(new_vaccinations, accuracy = 1)) %>%
  select(date, `Total Cases`, `New Cases`, `New Deaths`, `New Vaccinations`) %>%
  arrange(desc(date)) %>%
  head(5)
```




```{r}
covid_n %>%
  setNames(c("Main District", "District","Cases per 100,000", "Hospital Patients per 100,000", 
           "Deaths per 100,000", "Tests per 100,000", "Tracing", "Recoveries per 100,000")) %>%
  group_by(`Main District`) %>%
  summarise(`Cases per 100,000` = mean(`Cases per 100,000`),
            `Hospitalisations per 100,000` = mean(`Hospital Patients per 100,000`),
            `Deaths per 100,000` = mean(`Deaths per 100,000`),
            `Tests per 100,000` = mean(`Tests per 100,000`),
            `Recoveries per 100,000` = mean(`Recoveries per 100,000`)) %>%
  arrange(desc(`Cases per 100,000`)) %>%
  head(10)
```














